name: DifferentEvent2
on:
    issues:
        types: [opened]
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            - name: echo the issue details
              uses: echo ${{toJson(github.event)}}